[project]
name = "citycats"
authors = ["citycats devops"]
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2

[contracts.citycats-nft-mint]
path = "contracts/citycats-nft-mint.clar"
depends_on = ["citycats-nft"]

[contracts.citycats-nft]
path = "contracts/citycats-nft.clar"
depends_on = ["sip-009-nft-trait-standard", "commission-trait"]

[contracts.sip-009-nft-trait-standard]
path = "contracts/external/sip-009-nft-trait-standard.clar"
depends_on = []

[contracts.commission-trait]
path = "contracts/external/commission-trait.clar"
depends_on = []